In [ ]:
import numpy as np
import pandas as pd

#Работа с DataFrame

Данные для задач


```
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

##1. Создать DataFrame df c индексами из labels.

##2. Отобразить краткую основную информацию об df.

##3. Вывести первые 3 строки df.

##4. Вывести столбцы 'animal' и 'age' из df.

##5. Вывести строки с индексами ['d', 'e', 'i'] с информацией из стоблцов ['animal', 'age'].

##6. Вывести только те строки в которых количетсво посещений в ряде 'visits' больше 3.

##7. Вывести строки, где пропущен возраст.

##8. Вывести строки, где животное кошка в возрасте меньше 3.

##9. Вывести строки с возрастом от 2 до 4 включительно.

##10. Замените возраст в строке f на 1.5.

##11. Подсчитать сумму всех посещений.

##12. Найти средний возраст для каждого вида животного.

##13. Добавьте любую мтроку k на ваш выбор и удалите ее.

##14. Заменить в столбце priority параметр 'yes' и 'no' на True и False соответсвенно(Подсказка : метод .map)

##15. В столбце животные заменить 'snake' на 'python'(Подсказка : метод .replace)

##16. Для каждого вида животного и количества посещений найти средний возраст.

#Работа с файлами.

In [ ]:
titanik_passengers = pd.read_csv('titanic.csv', index_col='PassengerId')

##1. Опишите данный датасет: какое расределение женщин/мужчин в нем? Сколько пассажиров ехало в каждом классе? Какой средний/минимальный/максимальный возраст пассажиров?

## 2. Сгруппируйте записи по классам пассажиров, в каждой группе посчитайте средний возраст. Используйте метод ``pandas.DataFrame.groupby``.

###3. Слейте два датасета по колонке индекса.

In [ ]:
df_2 = pd.read_csv('titanic_surv.csv')

### 4. Сколько всего выживших пассажиров? Выживших пассажиров по каждому из полов? Постройте матрицу корреляций факта выживания, пола и возраста.